return {
  "NeogitOrg/neogit",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "sindrets/diffview.nvim",
  },
  keys = {
    { "<leader>gg", function() require("neogit").open() end, desc = "Neogit" },
    { "<leader>gc", function() require("neogit").open({ "commit" }) end, desc = "Commit" },
    { "<leader>gl", function() require("neogit").open({ "log" }) end, desc = "Log" },
    { "<leader>gp", function() require("neogit").open({ "push" }) end, desc = "Push" },
    { "<leader>gf", function() require("neogit").open({ "fetch" }) end, desc = "Fetch" },
  },
  config = function(_, opts)
    require("neogit").setup(opts)
    vim.api.nvim_create_autocmd("FileType", {
      pattern = "NeogitStatus",
      group = vim.api.nvim_create_augroup("neogit_worktrunk", { clear = true }),
      callback = function(ev)
        vim.keymap.set("n", "w", function()
          require("djinni.integrations.worktrunk_ui").create()
        end, { buffer = ev.buf, nowait = true, silent = true, desc = "Worktrunk" })
      end,
    })
  end,
  opts = {
    kind = "tab",
    disable_hint = true,
    disable_context_highlighting = true,
    disable_signs = false,
    remember_settings = false,
    use_per_project_settings = true,
    ignored_settings = {
      "NeogitPushPopup--force-with-lease",
      "NeogitPushPopup--force",
      "NeogitPullPopup--rebase",
      "NeogitCommitPopup--allow-empty",
      "NeogitRevertPopup--no-edit",
    },
    git = { timeout = 5000 },
    signs = {
      hunk = { "", "" },
      item = { ">", "v" },
      section = { ">", "v" },
    },
    integrations = {
      telescope = false,
      diffview = true,
      codediff = false,
      snacks = true,
    },
    diff_viewer = "diffview",
    mappings = {
      popup = {
        ["p"] = "PushPopup",
        ["P"] = "PullPopup",
        ["Z"] = "StashPopup",
        ["b"] = "BranchPopup",
        ["B"] = "BisectPopup",
        ["r"] = "RebasePopup",
        ["f"] = "FetchPopup",
        ["m"] = "MergePopup",
        ["M"] = "RemotePopup",
        ["X"] = "ResetPopup",
        ["A"] = "CherryPickPopup",
        ["v"] = "RevertPopup",
        ["w"] = false,
      },
      status = {
        ["q"] = "Close",
        ["1"] = "Depth1",
        ["2"] = "Depth2",
        ["3"] = "Depth3",
        ["4"] = "Depth4",
        ["<tab>"] = "Toggle",
        ["x"] = "Discard",
        ["s"] = "Stage",
        ["S"] = "StageUnstaged",
        ["<c-s>"] = "StageAll",
        ["u"] = "Unstage",
        ["U"] = "UnstageStaged",
        ["$"] = "CommandHistory",
        ["Y"] = "YankSelected",
        ["<c-r>"] = "RefreshBuffer",
        ["<enter>"] = "GoToFile",
        ["<c-v>"] = "VSplitOpen",
        ["<c-x>"] = "SplitOpen",
        ["<c-t>"] = "TabOpen",
        ["{"] = "GoToPreviousHunkHeader",
        ["}"] = "GoToNextHunkHeader",
      },
    },
    sections = {
      sequencer = { folded = false, hidden = false },
      untracked = { folded = false, hidden = false },
      unstaged = { folded = false, hidden = false },
      staged = { folded = false, hidden = false },
      stashes = { folded = true, hidden = false },
      unpulled_upstream = { folded = true, hidden = false },
      unmerged_upstream = { folded = false, hidden = false },
      unpulled_pushRemote = { folded = true, hidden = false },
      unmerged_pushRemote = { folded = false, hidden = false },
      recent = { folded = true, hidden = false },
      rebase = { folded = true, hidden = false },
    },
  },
}
