return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "helix",
    spec = {
      { "<leader>b", group = "Buffer" },
      { "<leader>c", group = "Code" },
      { "<leader>f", group = "Find" },
      { "<leader>g", group = "Git" },
      { "<leader>d", group = "Debug" },
      { "<leader>gx", group = "Conflict" },
      { "<leader>o", group = "Neowork" },
      { "<leader>ow", group = "Worktrunk" },
      { "<leader>r", group = "run/tasks" },
      { "<leader>t", group = "Tab" },
      { "<leader>tt", "<cmd>tabnew<cr>", desc = "New tab" },
      { "<leader>td", "<cmd>tabclose<cr>", desc = "Close tab" },
      { "<leader>tk", "<cmd>tabclose<cr>", desc = "Kill tab" },
      { "<leader>yf", function()
        local path = vim.fn.expand("%:.")
        vim.fn.setreg("+", path)
        vim.fn.setreg('"', path)
      end, desc = "Yank file path" },
      { "<leader>w", group = "Window" },
      { "<leader>wh", "<C-w>h", desc = "Window left" },
      { "<leader>wj", "<C-w>j", desc = "Window down" },
      { "<leader>wk", "<C-w>k", desc = "Window up" },
      { "<leader>wl", "<C-w>l", desc = "Window right" },
      { "<leader>ws", "<C-w>s", desc = "Split horizontal" },
      { "<leader>wv", "<C-w>v", desc = "Split vertical" },
      { "<leader>wq", "<C-w>q", desc = "Close window" },
      { "<leader>wH", "<C-w><", desc = "Decrease width" },
      { "<leader>wL", "<C-w>>", desc = "Increase width" },
      { "<leader>wJ", "<C-w>-", desc = "Decrease height" },
      { "<leader>wK", "<C-w>+", desc = "Increase height" },
      { "[", group = "Prev" },
      { "]", group = "Next" },
      { "g", group = "Goto" },
      { "ga", group = "AI" },
      { "gac", desc = "Task with file context" },
      { "ga", group = "AI", mode = "v" },
      { "gav", desc = "Task with selection", mode = "v" },
      { "gas", desc = "Send selection to chat", mode = "v" },
    },
  },
}
